### ISSUE TITLE
Resultado incorrecto debido a una proyección que no preserva el área

### ISSUE THREAD

**Issue by chrisjbillington** [pacosalces/geomx#1]
El código calcula el centroide en coordenadas de latitud y longitud, lo que da como resultado un centroide demasiado al norte. Según [esta respuesta de stackexchange](https://gis.stackexchange.com/questions/372564/userwarning-when-trying-to-get-centroid-from-a-polygon-geopandas), primero debe proyectar a una proyección que preserve el área:
```python
mx_junto["centroide"] = mx_junto.to_crs('+proj=cea').centroid.to_crs(mx_junto.crs)
```

![image](https://user-images.githubusercontent.com/1044087/189787014-61b04b0c-94ea-4006-8aed-3d0b304c3a7d.png)

**Comment by pacosalces** [comment]
Gracias @chrisjbillington! Ya agregue la correccion en 4118a58c3e8a71e4d0d65a50ff7cdad75cd68d41. Voy a cerrar el problema.
